# Generated by Django 2.2.10 on 2020-05-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(default='no text', max_length=20)),
                ('content', models.TextField(default='no text')),
                ('emotion', models.IntegerField(choices=[(1, '😍행복해요'), (2, '🙃보통이에요'), (3, '😑별로에요'), (4, '😭슬퍼요'), (5, '😡화나요')], default=2)),
                ('WBC', models.IntegerField(default=0)),
                ('neutrophil', models.IntegerField(default=0)),
                ('RBC', models.IntegerField(default=0)),
                ('PT', models.IntegerField(default=0)),
                ('public', models.BooleanField(default=False)),
            ],
        ),
    ]
